// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DataTableGridController from "./data_table_grid_controller"
application.register("data-table-grid", DataTableGridController)

import DateController from "./date_controller"
application.register("date", DateController)

import DatetimeController from "./datetime_controller"
application.register("datetime", DatetimeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import InfinitePageController from "./infinite_page_controller"
application.register("infinite-page", InfinitePageController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)

import TimeController from "./time_controller"
application.register("time", TimeController)

import ToastrController from "./toastr_controller"
application.register("toastr", ToastrController)

import TurbolinksFormController from "./turbolinks_form_controller"
application.register("turbolinks-form", TurbolinksFormController)

import ValidationController from "./validation_controller"
application.register("validation", ValidationController)
