require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/shein_orders", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SheinOrder. As you add validations to SheinOrder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SheinOrder.create! valid_attributes
      get shein_orders_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      shein_order = SheinOrder.create! valid_attributes
      get shein_order_url(shein_order)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_shein_order_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      shein_order = SheinOrder.create! valid_attributes
      get edit_shein_order_url(shein_order)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SheinOrder" do
        expect {
          post shein_orders_url, params: { shein_order: valid_attributes }
        }.to change(SheinOrder, :count).by(1)
      end

      it "redirects to the created shein_order" do
        post shein_orders_url, params: { shein_order: valid_attributes }
        expect(response).to redirect_to(shein_order_url(SheinOrder.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SheinOrder" do
        expect {
          post shein_orders_url, params: { shein_order: invalid_attributes }
        }.to change(SheinOrder, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post shein_orders_url, params: { shein_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested shein_order" do
        shein_order = SheinOrder.create! valid_attributes
        patch shein_order_url(shein_order), params: { shein_order: new_attributes }
        shein_order.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the shein_order" do
        shein_order = SheinOrder.create! valid_attributes
        patch shein_order_url(shein_order), params: { shein_order: new_attributes }
        shein_order.reload
        expect(response).to redirect_to(shein_order_url(shein_order))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        shein_order = SheinOrder.create! valid_attributes
        patch shein_order_url(shein_order), params: { shein_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested shein_order" do
      shein_order = SheinOrder.create! valid_attributes
      expect {
        delete shein_order_url(shein_order)
      }.to change(SheinOrder, :count).by(-1)
    end

    it "redirects to the shein_orders list" do
      shein_order = SheinOrder.create! valid_attributes
      delete shein_order_url(shein_order)
      expect(response).to redirect_to(shein_orders_url)
    end
  end
end
